import type { Metadata } from "next";
import { Poppins as FontPoppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/Navbar";
import Footer from "@/shared/Footer";
import { NextIntlClientProvider } from "next-intl";
// import en from "@/../messages/en.json";
// import id from "@/../messages/id.json";

// const messages: Record<string, typeof en> = { en, id };


const poppins = FontPoppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Gunakan `weight`, bukan `weights`
});

export const metadata: Metadata = {
  title: "48Prodigy",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string; };
}

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body className={poppins.className}>
        <NextIntlClientProvider locale={locale}>
          <Navbar />
        </NextIntlClientProvider>
        {children}
        <Footer />
      </body>
    </html>
  );
}